cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

dyvas/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', accounts_views.register, name='register'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),
    
    path('', include('shop.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models
from shop.models import Product

# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['-date_added']

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

cart/forms.py
from django import forms
from shop.models import Product


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart            = Cart(request)
    product         = get_object_or_404(Product, id=product_id)
    form            = CartAddProductForm(request.POST)
    
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart            = Cart(request)
    product         = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart    = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    context = {
        'cart': cart,
    }
    return render(request, 'cart/cart_detail.html', context)

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}        

<div class="container">
    <h2>Your Shopping Cart</h2>
    <table class="table my-3 table-striped">
        <thead class="thead-light">
            <tr>
            <th scope="col">Image</th>
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>
            <th scope="col">Remove</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <th scope="row">
                   <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt=""></a>
                </th>
                <td>{{ product.name }}</td>
                <td>
                    <!-- {% if item.quantity < product.stock %} -->
                    <form method="POST" action="{% url 'cart:cart_add' product.id %}">{% csrf_token %}
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <button class="btn btn-primary" type="submit" value="update">Update</button>
                    </form>
                    <!-- {% endif %} -->
                </td>
                <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
                <td class="num">&#8358; {{ item.price|intcomma }}</td>
                <td class="num">&#8358; {{ item.total_price|intcomma }}</td>
            </tr>
            {% endwith %}
            {% endfor %}
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td> <strong>Total</strong> </td>
                <td><strong>&#8358; {{ cart.get_total_price|intcomma }}</strong></td>
            </tr>
        </tbody>
    </table>
    <p>
        
        <a class="btn btn-primary mr-2" href="{% url 'shop:product_list' %}">Continue Shopping</a>
        <a class="btn btn-primary" href="{% url 'orders:order_create' %}">Checkout</a>
    </p>
</div>
    
{% endblock %}